ScrollReveal().reveal('wave')
ScrollReveal().reveal('header h1', { delay: 500 })
ScrollReveal().reveal('header h2', { delay: 600 })
ScrollReveal().reveal('main', { delay: 2000 })
ScrollReveal().reveal('p.contact', { delay: 2100 })