ScrollReveal().reveal('wave')
ScrollReveal().reveal('header h1', { delay: 200 })
ScrollReveal().reveal('p.contact', { delay: 300 })
ScrollReveal().reveal('header h2', { delay: 400 })
ScrollReveal().reveal('footer li', { delay: 500 })
ScrollReveal().reveal('main', { delay: 500 })