ScrollReveal().reveal('wave')
ScrollReveal().reveal('header h1', { delay: 400 })
ScrollReveal().reveal('p.aboutAndContact', { delay: 600 })
ScrollReveal().reveal('header h2', { delay: 800 })
ScrollReveal().reveal('main', { delay: 1000 })